In [15]:
import numpy as np
x = np.array([[3, 3, 3, 3, 3], [3, 3, 3, 3, 3], [3, 3, 3, 3, 3],  [3, 3, 3, 3, 3],  [3, 3, 3, 3, 3]])

In [16]:
print(x)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [17]:
x.shape

(5, 5)

In [18]:
import numpy as np

In [19]:
y = np.power(x, 2)

In [20]:
print(y)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
