In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])

In [4]:
a * 3

array([3, 6, 9])

In [5]:
a + 2

array([3, 4, 5])

In [6]:
b = np.array([2, 2, 0])

In [7]:
a + b

array([3, 4, 3])

In [8]:
a / b

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.5, 1. , inf])

In [9]:
a * b

array([2, 4, 0])

# 内積

In [10]:
np.dot(a, b) 

6

# ０〜１０までを２ごとに区切る

In [11]:
np.arange(0, 10 ,2) #(始点、終点、　間隔）　

array([0, 2, 4, 6, 8])

# 0~10の区間を15等分

In [12]:
np.linspace(0, 10 ,15) 

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

# 2次元配列

In [13]:
c = np.array([[1, 2, 3], [4, 5, 6]])

In [14]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
c.shape

(2, 3)

In [16]:
np.sum(c) #和を求める　 #1+2+3+4+5+6

21

In [17]:
# 列ごとの和　　#軸(axis)を指定
np.sum(c, axis = 1) #6=1+2+3 #15=4+5+6

array([ 6, 15])

In [18]:
c.reshape(3, 2) #配列の形状を変える

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
c.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# 3次元配列

In [20]:
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
              [[13, 14, 15], [16, 17, 18], [19,20,21], [22, 23, 24]]])

In [21]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [22]:
d.shape

(2, 4, 3)

# 乱数

In [23]:
np.random.randn() #randn関数→標準正規分布に従った値を返す

0.5278403748664641

In [24]:
np.random.rand() #rand関数→0~1までの値の中で乱数を返す

0.62223984913184

In [25]:
np.random.randn(2, 3) #任意の形状の配列の要素を乱数で埋めたものを出力

array([[ 1.52495004,  0.9413899 , -0.21650143],
       [ 0.51495208,  1.02699895,  0.57781244]])

# インデックスとスライシング

In [26]:
a

array([1, 2, 3])

In [27]:
a[0]

1

In [28]:
a

array([1, 2, 3])

In [29]:
a[1]

2

In [30]:
a[2]

3

In [31]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
c[0,0]

1

In [33]:
c[0,2]

3

In [34]:
c[1,2]

6

In [35]:
d = np.array([0, 5, 2, 7, 1, 9])

In [36]:
d[1:5]

array([5, 2, 7, 1])

In [37]:
d[1:3]

array([5, 2])

In [38]:
d[0: 5: 2]

array([0, 2, 1])

In [39]:
d[::-1]

array([9, 1, 7, 2, 5, 0])

# ブロードキャスティング

In [40]:
a + c

array([[2, 4, 6],
       [5, 7, 9]])

In [41]:
a * c

array([[ 1,  4,  9],
       [ 4, 10, 18]])

# NumPyの高速演算

In [45]:
import numpy as np

In [46]:
import time

In [47]:
def calculta_time():
    a = np.random.randon(100000)
    b = list(a)
    start_time = time.time()
    for _ in range(1000):
        sum_1 = np.sum(a)
    print("Using NumPy¥\t %f sec" % (time.time() - start_time))
    start_time = time.time()
    for _ in range(1000):
        sume_2 = sum(b)

In [48]:
import numpy as np

In [49]:
a = np.random.randn(10000000)

In [50]:
%timeit np.sum(a)

5.26 ms ± 36.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [51]:
%timeit sum(a)

925 ms ± 1.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
